# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 05:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='listing',
            name='document',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
    ]
