# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_bought'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bought',
            name='seller',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
