# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_listing_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='status',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
