# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 17:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_bought_trans_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bought',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bought',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='listings.Listing'),
        ),
    ]
