# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 23:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_auto_20171120_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bought',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sellers.Seller'),
        ),
    ]
