# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_bought_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='bought',
            name='redeemed',
            field=models.BooleanField(default=False),
        ),
    ]
