# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 02:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0012_bought_redeemed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('expire', models.DateTimeField()),
                ('bought', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.Bought')),
            ],
        ),
    ]
