# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 06:00
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0002_auto_20171106_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='zip',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')]),
        ),
    ]
