# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 16:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0003_auto_20171106_0600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='zip',
            new_name='zipp',
        ),
    ]
