# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0004_auto_20171106_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='merch',
            field=models.CharField(default='', max_length=50),
        ),
    ]
