# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0005_seller_merch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='merch',
            field=models.CharField(default='', max_length=50),
        ),
    ]
