# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0006_auto_20171204_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
